### PR TITLE
Feature reddit

### PR DESCRIPTION
**Pull request by amita-roy**
## We have created 3 models User, Post and Comment

- Added association User has many posts and User has many comments
- Added association Post belongs to a user and Post has many comments
- Added association Comment belongs to a user and Comment belongs to a post
- Added validation for all the three models

### CODE REVIEW

**Review by kobiyoyo — CHANGES_REQUESTED** [review]
## Hi Team    
#### Great Job so far, everything works fine, but there are a few more things required. 
### General 
- [x] Lets activate linter checks for this project
### Make changes and submit another code review request.
*Happy coding* 
(Any questions Feel free to contact me on slack @kobiyoyo)

**Comment by amita-roy** [comment]
Added Rubocop for linting

**Review by andresporras3423 — CHANGES_REQUESTED** [review]
### Status: Changes Required :recycle:
**Hello Ahmad Muhammad & Amita Roy** 
Nice job with your new submission :muscle:  :muscle: 
Your project meets most of the requirements :clap: :clap: :clap:  
We still need to fix some details:

- [x]  Add a screenshot in your README file
- [x] Remove password uniqueness validation
- [x] Your email validation should not allow something like "aaaa@aaaa" as a valid email. An acceptable validation should make sure your email has the next structure: <anystring>@<anystring>.<anystring>

Please request another review once you are ready! :+1: 

Happy coding :relaxed:

Oscar Andrés Russi Porras

**Review by kobiyoyo — APPROVED** [review]
# Project Approved :thumbsup:
## Hello Team  ,  you have done a brilliant job with this project. :clap:
#### You can merge !!!

**Pull request merged**
